name: "Publish Release"

on:
  release:
    types: ["published"]

jobs:
  publish_windows:
    
    runs-on: windows-latest

    env:
      WORK_DIR_PATH: ${{ github.RUNNER_TEMP }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Compile with Maven and jlink
        run: mvn clean javafx:jlink

      - name: Package
        run: |
          New-Item -ItemType Directory -Path "$env:WORK_DIR_PATH\build"
          Move-Item -Path ".\target\APIxels.zip" -Destination "$env:WORK_DIR_PATH\build\APIxels-win.zip"

      - name: "Upload Packages To Github Release"
        uses: "ncipollo/release-action@v1.14.0"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ env.WORK_DIR_PATH }}\build\*
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.

  publish_linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Compile with Maven and jlink
        run: mvn clean javafx:jlink

      - name: Package
        run: |
          mkdir -p ~/build
          mv ./target/APIxels.zip ~/build/APIxels-linux.zip

      - name: "Upload Packages To Github Release"
        uses: "ncipollo/release-action@v1.14.0"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "~/build/*"
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.

  publish_macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Compile with Maven and jlink
        run: mvn clean javafx:jlink

      - name: Package
        run: |
          mkdir -p ~/build
          mv ./target/APIxels.zip ~/build/APIxels-osx.zip

      - name: "Upload Packages To Github Release"
        uses: "ncipollo/release-action@v1.14.0"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "~/build/*"
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          omitBodyDuringUpdate: true # We don't want to update the body of the release.
          omitNameDuringUpdate: true # We don't want to update the name of the release.